name = "case-management"
main = "./src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./../frontend/dist"
binding = "ASSETS"
run_worker_first=false
not_found_handling = "single-page-application"

[vars]
ENV = "production"
# 以下敏感信息将通过 wrangler secret 命令设置
# 请运行以下命令设置密钥:
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_USERNAME
# wrangler secret put ADMIN_PASSWORD 
# wrangler secret put TURNSTILE_SECRET_KEY

# 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "case-management"
database_id = ""

# R2存储配置
[[r2_buckets]]
binding = "CASE_FILES"
bucket_name = "case-files" 
